Repository Azure/aml-registermodel, pull requests merged in 2020-05, with the labels that each got.

#6 Added input validation & unit tests
  .cloud/.azure/registermodel.json
  .github/workflows/python.yml
  .gitignore
  Dockerfile
  README.md
  code/entrypoint.sh
  code/main.py
  code/schemas.py
  code/utils.py
  tests/test_main.py
  tests/test_utils.py
Labels: enhancement

#10 Ashishonce/integration test
  .cloud/.azure/test/test_registermodel.json
  .cloud/.azure/test/test_workspace.json
  .github/workflows/integration.yml
Labels: enhancement

#8 Local model registration
  .cloud/.azure/test/test_registermodel_fromlocal.json
  .github/workflows/integration.yml
  README.md
  action.yml
  code/main.py
  code/utils.py
  tests/testlocalmodel.pkl
Labels: enhancement

#11 Update README.md inline with other Azure actions
  README.md
Labels: documentation

#12 Update azureml-sdk to 1.5.0
  Dockerfile
Labels: enhancement

#13 remove ls
  .gitattributes
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
  SECURITY.md
  code/entrypoint.sh
Labels: bug

#14 Upgrade to Azure ML SDK 1.6.0
  Dockerfile
Labels: enhancement
